version: '3.8'

services:
  couchpotatoplayer:
    image: ghcr.io/bladestar2105/couchpotatoplayer-web:latest
    container_name: couchpotatoplayer
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
