events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Original block from nginx.conf that fails for binary segments
        location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$ {
            # Extract target url the exact same way as /proxy/
            # In /proxy/, proxy_pass works correctly!
            # Let's verify this!
            # Wait, /proxy/ block in nginx.conf works for everything else?

            resolver 8.8.8.8 8.8.4.4 valid=300s;
            resolver_timeout 5s;

            set $target_url "";
            if ($request_uri ~* "^/proxy/(.*)$") {
                set $target_url $1;
            }
            if ($target_url = "") { return 400 "Missing target URL"; }

            # Wait, if `curl -I "https://stream.team-ei.de/movie/yoshisan/Ss21051988/1.mp4"`
            # returns 502 from Caddy directly, then the 502 is NOT NGINX's fault!
            # IT'S THE UPSTREAM SERVER'S FAULT!
            # But wait! Why does the issue say Nginx returns 502?
            # User provided access logs:
            # 192.168.178.37 - - [10/Mar/2026:21:33:23 +0000] "GET /proxy/https://stream.team-ei.de/movie/yoshisan/Ss21051988/1.mp4 HTTP/1.1" 502 ...
            # Could it be that the proxy block is completely broken for all domains, or just this one?

        }
    }
}
