events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # WOW! `curl -I "http://localhost:80/proxy/https://stream.team-ei.de/"` returned 200 OK!
        # BUT `curl -I "http://localhost:80/proxy/https://stream.team-ei.de/movie/yoshisan/Ss21051988/1.mp4"` returns 502!
        # WHY? Because the `.mp4` URL hits the REGEX block!
        # location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$
        # So the REGEX block is broken, but the normal /proxy/ block works!

        # Let's verify!
    }
}
