content = <<~TEXT
// Autogenerated from Pigeon
import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif
TEXT

patched = content

# Replace imports at top: "import Flutter\nimport UIKit" with platform-guarded version
patched = patched.gsub(
  "import Flutter\nimport UIKit",
  "#if os(iOS)\nimport Flutter\nimport UIKit\n#elseif os(tvOS)\nimport Flutter\nimport UIKit\n#endif"
)
puts patched
