content = <<~TEXT
// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif
TEXT

patched = content
error_b = "#if os(iOS)\nimport Flutter\n#elseif os(macOS)\nimport FlutterMacOS\n#else\n#error(\"Unsupported platform.\")\n#endif"
fix_b   = "#if os(iOS) || os(tvOS)\nimport Flutter\n#elseif os(macOS)\nimport FlutterMacOS\n#endif"
patched = patched.gsub(error_b, fix_b)
puts patched
