events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;
        location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$ {
            set $target_url "";
            if ($request_uri ~* "^/proxy/(.*)$") {
                set $target_url $1;
            }
            add_header X-Debug-Target-Url $target_url always;
            add_header X-Debug-Request-Uri $request_uri always;
            return 200 "OK\n";
        }
    }
}
