events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;
        location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$ {
            resolver 8.8.8.8;
            set $target_url "";
            set $target_host "";
            if ($request_uri ~* "^/proxy/(https?://([^/]+)(.*))$") {
                set $target_url $1;
                set $target_host $2;
                set $target_uri $3;
            }
            # Add host header because some upstream servers drop requests with default host
            proxy_set_header Host $target_host;
            rewrite ^ $target_uri break;
            proxy_pass $target_url;
            proxy_ssl_server_name on;
        }
    }
}
