events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Test rewriting properly
        location /proxy/ {
            resolver 8.8.8.8;
            set $target_url "";
            if ($request_uri ~* "^/proxy/(.*)$") {
                set $target_url $1;
            }
            # Instead of passing the whole $target_url directly, maybe we pass it WITHOUT variables? No.
            # Look at this stackoverflow answer:
            # "Since proxy_pass with a variable doesn't append query args automatically we have to pass the exact URI.
            # But wait, we used $target_url which INCLUDES the query args."
            # Wait, if we use proxy_pass $target_url, why does Nginx use "/proxy/https:/stream.team-ei.de/movie/yoshisan/Ss21051988/1.mp4?"
            # Because $target_url might NOT be recognized as a full URL?
            # Why? Because $request_uri is NOT "https://..." but "https:/..."?
            # Let's log $target_url!
            add_header X-Target-Url $target_url always;
            add_header X-Request-Uri $request_uri always;

            # proxy_pass $target_url;
        }
    }
}
