events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;
        location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$ {
            resolver 8.8.8.8;
            set $target_url "";
            if ($request_uri ~* "^/proxy/(.*)$") {
                set $target_url $1;
            }
            proxy_pass $target_url;
            proxy_ssl_server_name on;
        }
    }
}
