events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # In test2-nginx.conf (which wraps nginx.conf),
        # curl -I "http://localhost:80/proxy/https://google.com/video.mp4" returned 404!
        # WHY did it return 404? Because google.com returned 404!
        # Which means it reached google.com correctly!

        # Let's test reaching stream.team-ei.de with the exact same config!
    }
}
