events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;
        location /proxy/ {
            resolver 8.8.8.8;
            set $target_url "";
            set $target_host "";
            if ($request_uri ~* "^/proxy/(https?://([^/]+)(.*))$") {
                set $target_url $1;
                set $target_host $2;
            }
            # Look at how it behaves in the original /proxy/ block
            proxy_pass $target_url;
            proxy_ssl_server_name on;
        }
    }
}
