events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Test rewriting the exact config in the regex block from test2
        location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$ {
            resolver 8.8.8.8 8.8.4.4 valid=300s;
            resolver_timeout 5s;

            set $target_url "";
            if ($request_uri ~* "^/proxy/(.*)$") {
                set $target_url $1;
            }
            if ($target_url = "") { return 400 "Missing target URL"; }

            # This is how you correctly pass a URL extracted from URI inside proxy_pass
            # when using variables.
            # IN THE ORIGINAL location /proxy/, it is a PREFIX match.
            # "A request URI is passed to the server as follows: If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive."
            # BUT proxy_pass has NO URI here because it's a variable!
            # Wait, if `proxy_pass $target_url` is a variable without URI, it uses original request URI!
            # Which is EXACTLY why both location blocks send `/proxy/https:/...`!
            # Wait! If BOTH location blocks send `/proxy/https:/...`, why did `stream.team-ei.de/` work?
            # BECAUSE IT WAS A DIFFERENT UPSTREAM SERVER THAT HAPPENED TO IGNORE `/proxy/https:/`?
            # Or wait, look at `nginx.conf` again for `/proxy/`!
            # "proxy_pass $target_url;"

            # Wait... if `proxy_pass $target_url` is used, the ONLY WAY to make it not send the original URI is to change the NGINX configuration to REWRITE the URI before proxy_pass!
        }
    }
}
