events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Why did it return 502 for stream.team-ei.de but NOT for google.com?
        # Let's check with `curl -v "http://localhost:80/proxy/https://stream.team-ei.de/"`
        # Because we saw that `/proxy/` block returned 502 too!
    }
}
