content = <<~TEXT
//
//  messages.g.swift
//  Autogenerated from Pigeon (v10.1.6), do not edit directly.
//  See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif
TEXT

patched = content

# Replace regex matching varying spaces:
patched = patched.gsub(
  /#if os\(iOS\)\n\s*import Flutter\n#elseif os\(macOS\)\n\s*import FlutterMacOS\n#else\n\s*#error\("Unsupported platform."\)\n#endif/,
  "#if os(iOS) || os(tvOS)\n  import Flutter\n#elseif os(macOS)\n  import FlutterMacOS\n#endif"
)
puts patched
