events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Test rewriting the exact config in the normal block from test2
        location /proxy/ {
            resolver 8.8.8.8 8.8.4.4 valid=300s;
            resolver_timeout 5s;

            set $target_url "";
            if ($request_uri ~* "^/proxy/(.*)$") {
                set $target_url $1;
            }
            if ($target_url = "") { return 400 "Missing target URL"; }

            proxy_pass $target_url;
            proxy_ssl_server_name on;
        }
    }
}
