events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Test rewriting the exact config in the regex block from test2
        location /proxy/ {
            resolver 8.8.8.8 8.8.4.4 valid=300s;
            resolver_timeout 5s;

            # This is how you correctly pass a URL extracted from URI:
            # You must not use $request_uri and proxy_pass together when expecting the URI to be replaced.
            # INSTEAD of using $request_uri, let's use a rewrite block!
            rewrite ^/proxy/(.*)$ /$1 break;

            # Wait, if we rewrite, $1 will be "https://..."
            # proxy_pass CAN take a variable, but if we rewrite we can just do:
            # Wait, proxy_pass doesn't support $1 directly unless it's a variable.
            # But we can set a variable from the regex in location!
        }

        location ~ ^/proxy/(?<target_url>https?://.*)$ {
            resolver 8.8.8.8 8.8.4.4 valid=300s;
            resolver_timeout 5s;

            # This works if the URL has one slash or two slashes collapsed?
            # Actually, `https://` gets collapsed to `https:/` in NGINX $uri!
            # So the regex should match `https?://?`
        }
    }
}
