events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Test rewriting the exact config in the regex block from test2
        location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$ {
            # Let's see what proxy_pass does if we pass JUST the domain!
            resolver 8.8.8.8 8.8.4.4 valid=300s;
            resolver_timeout 5s;

            set $target_url "";
            set $target_origin "";
            set $target_path "";
            if ($request_uri ~* "^/proxy/(https?://([^/]+)(.*))$") {
                set $target_url $1;
                set $target_origin "https://$2";
                set $target_path $3;
            }
            if ($target_url = "") { return 400 "Missing target URL"; }

            # Rewrite URI to $target_path
            rewrite ^ $target_path break;

            proxy_pass $target_origin;
            proxy_ssl_server_name on;
        }
    }
}
