events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;

        # Why is the user reporting 502 for THIS specific URL when NO matter what I do,
        # EVEN curl -I directly to the server returns 502!
        # wait! Did `curl -I "https://stream.team-ei.de/movie/yoshisan/Ss21051988/1.mp4"` return 502?
        # YES!
        # So the upstream server is ACTUALLY broken!
        # But wait! The issue says:
        # "192.168.178.37 - - [10/Mar/2026:21:33:23 +0000] "GET /proxy/https://stream.team-ei.de/movie/yoshisan/Ss21051988/1.mp4 HTTP/1.1" 502 ..."
        # Why did the user report this?
        # Let's read the issue title/description again. Ah, there is NO title, just the log lines!
        # But we know that if we use the original `nginx.conf`, the NGINX block fails to route properly and passes `"/proxy/https:/..."` which causes a 502!
        # Wait, if `"/proxy/https:/stream.team-ei.de/movie/..."` causes a 502 from Caddy, that's because Caddy doesn't have a route for `/proxy/...`!
        # But if we fix it to send `"/movie/yoshisan/Ss21051988/1.mp4?"`, Caddy STILL returns 502!
        # Maybe Caddy requires a specific User-Agent?
        # Maybe Caddy blocks HEAD requests? Let's try GET!
    }
}
