content = <<~TEXT
//
//  messages.g.swift
//  Autogenerated from Pigeon (v10.1.6), do not edit directly.
//  See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif
TEXT

patched = content

error_b = '#if os(iOS)' + "\n" + 'import Flutter' + "\n" + '#elseif os(macOS)' + "\n" +
          'import FlutterMacOS' + "\n" + '#else' + "\n" + '#error(' + '"' + 'Unsupported platform.' + '"' + ')' + "\n" + '#endif'
fix_b   = '#if os(iOS) || os(tvOS)' + "\n" + 'import Flutter' + "\n" + '#elseif os(macOS)' + "\n" +
          'import FlutterMacOS' + "\n" + '#endif'

patched = patched.gsub(error_b, fix_b)
puts patched
