events {}
http {
    error_log /app/error.log debug;
    server {
        listen 80;
        location ~* ^/proxy/.*\.(ts|mp4|mkv|m4s|mp4a|mp4v)(\?.*)?$ {
            resolver 8.8.8.8;
            set $target_url "";
            set $target_host "";
            if ($request_uri ~* "^/proxy/(https?://([^/]+)(.*))$") {
                set $target_url $1;
                set $target_host $2;
            }
            # Add host header and rewrite
            # Wait, Nginx says: "If proxy_pass is specified without a URI, the request URI is passed to the server in the same form as sent by a client... OR if a rewrite rule changed it, it passes the changed URI."
            #BUT if $target_url is considered to HAVE a URI, then the changed URI is NOT passed!
            # The URI part of $target_url is $3.
            # If $target_url is just the scheme and host, proxy_pass will append the current $uri !
            # So let's extract scheme and host to $target_origin, and set URI via rewrite!
            set $target_origin "";
            if ($request_uri ~* "^/proxy/(https?://[^/]+)") {
                set $target_origin $1;
            }
            rewrite ^/proxy/https?://[^/]+(.*)$ $1 break;
            proxy_pass $target_origin;
            proxy_ssl_server_name on;
        }
    }
}
