# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

source 'https://github.com/CocoaPods/Specs.git'

def shared_pods(config)
  pod 'KSPlayer', :git => 'https://github.com/kingslay/KSPlayer.git'
  pod 'DisplayCriteria', :git => 'https://github.com/kingslay/KSPlayer.git', :modular_headers => true
  pod 'FFmpegKit', :git => 'https://github.com/kingslay/FFmpegKit.git', :tag => '6.1.3', :modular_headers => true
  pod 'Libass', :git => 'https://github.com/kingslay/FFmpegKit.git', :tag => '6.1.3'
  pod 'Libmpv', :git => 'https://github.com/kingslay/FFmpegKit.git', :tag => '6.1.3'
  pod 'OpenSSL', :git => 'https://github.com/kingslay/FFmpegKit.git', :tag => '6.1.3'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'CouchPotatoPlayer' do
  platform :tvos, min_ios_version_supported
  config = use_native_modules!
  shared_pods(config)

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

target 'CouchPotatoPlayer-iOS' do
  platform :ios, min_ios_version_supported
  config = use_native_modules!
  shared_pods(config)

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
