name: Web Preview Build

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-web-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t couchpotatoplayer-web:${{ github.sha }} .

      # You can add steps here to push the image to a registry like GitHub Packages (ghcr.io)
      # or deploy it to a staging environment for PR previews.
